trying new connection string
first build failed, error given:
Error: Resource 'myApp' doesn't exist. Resource should exist before deployment.
trying new string to find if error occurs for because it doesn't understand resource string or cant find app.